# -*- coding: utf-8 -*-
"""Proyek Predictive Analytics (Palm Oil).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPEIkKZcczdk37eeKv49x0feRh7wiy_I

# Proyek Predictive Analytics: Palm Oil Price
- **Nama:** Putri Mentari
- **Email:** ri.mentaripm@gmail.com
- **ID Dicoding:** pmentari

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

"""## Data Loading"""

from google.colab import drive
drive.mount('/content/drive')

"""Loading data yang disimpan di googlr drive"""

palmoil_df = pd.read_csv('/content/drive/MyDrive/Laskar Ai/Palm Oil Futures Historical Data.csv')
palmoil_df.T

palmoil_df.info()

"""Pada data di atas, diketahui terdapat 670 baris dan 7  kolom data. Namun, seluruh variabel yang seharusnya angka masih bertipe object, maka selanjutnya perlu untuk mengubah tipe datanya sesuai dengan karakteristik dari variabel.

Pengecekan missing values
"""

palmoil_df.isna().sum()

"""DIketahui terdapat 19 missing values pada kolom Vol.

Ringkasan statistik dekriptif
"""

palmoil_df.describe()

"""Statistik deskriptif di atas menunjukkan jumlah nilai unik pada setiap kolom, di mana kolom Vol. memiliki nilai unik paling sedikit adalah 229 nilai unik.

Selanjutnya, kita akan melihat tren fluktuasi harga secara historis (berdasarkan data yang belum dibersihkan)

Mengurutkan data berdasarkan tanggal
"""

palmoil_df = palmoil_df.sort_values(by='Date')

"""Mengurutkan data price dengan membuat salinan sementara"""

palmoil_df['Price_temp'] = palmoil_df['Price'].str.replace(',', '')
palmoil_df['Price_temp'] = palmoil_df['Price_temp'].astype(float)

sorted_price_labels = palmoil_df.sort_values(by='Price_temp')['Price'].unique()

"""Membuat grafik tren"""

plt.figure(figsize=(12, 6))
plt.plot(palmoil_df['Date'], palmoil_df['Price_temp'], linestyle='-', color='blue', label='Palm Oil Historical Data')

plt.title('Pergerakan Harga Palm Oil dari Waktu ke Waktu')
plt.xlabel('Tanggal')
plt.ylabel('Harga')
plt.grid(True)
plt.legend()

step = 100
plt.xticks(ticks=range(0, len(palmoil_df['Date']), step),
           labels=palmoil_df['Date'][::step], rotation=45)

plt.tight_layout()
plt.show()

"""Grafik di atas menunjukkan tren fluktuasi harga palm oil. Data dalam grafik diurutkan berdasarkan tanggal.
Pada Q1-Q2 tahun 2022, harga palm oil menunjukkan tren peningkatan. Harga palm oil pada Q3 harga palm oil mengalami penurunan signifikan. Tren ini berlanjut hingga Q3 tahun 2024 dengan fluktuasi harga yang cenderung stagnan.

## Data Preparation

Konversi data dari tipe object ke integer dan datetime
"""

kolom_int = ['Price', 'Open', 'High', 'Low', 'Change %']
kolom_tanggal = 'Date'

for col in kolom_int:
    palmoil_df[col] = (
        palmoil_df[col]
        .replace(',', '', regex=True)
        .astype(str).str.strip()
    )
    palmoil_df[col] = pd.to_numeric(palmoil_df[col], errors='coerce').fillna(0).astype(int)

palmoil_df[kolom_tanggal] = pd.to_datetime(palmoil_df[kolom_tanggal], errors='coerce')

"""Konversi tipe data untuk Vol. dan sesuaikan satuannya"""

def parse_volume(val):
    if isinstance(val, str):
        val = val.replace(',', '').strip().upper()
        if 'K' in val:
            try:
                return int(float(val.replace('K', '')) * 1000)
            except:
                return None
        elif val.replace('.', '', 1).isdigit():
            return int(float(val))
    return None  # Untuk N/A atau None

palmoil_df['Vol.'] = palmoil_df['Vol.'].apply(parse_volume)

"""Mengisi missing values di kolom Vol. dengan nilai median dari Vol."""

median_value = palmoil_df['Vol.'].median()
palmoil_df['Vol.'] = palmoil_df['Vol.'].fillna(median_value)

palmoil_df.isna().sum()

"""Sudah tidak ada missing values di kolom Vol.

Menghapus Price_temp yang sebelumnya digunakan untuk membuat grafik tren
"""

palmoil_df.drop(columns=['Price_temp'], inplace=True)

"""Melihat distribusi data"""

numeric_columns = palmoil_df.select_dtypes(include='number').columns

plt.figure(figsize=(15, 10))
for i, column in enumerate(numeric_columns, 1):
    plt.subplot(2, 3, i)
    sns.histplot(palmoil_df[column], kde=True, bins=30)
    plt.title(f'Distribution of {column}')

plt.tight_layout()
plt.show()

"""Distribusi nilai untuk variabel Price, Open, High, dan Low cenderung normal, sementara variabel Vol. memiliki distribusi skewed ke kanan dengan dominasi nilai di bawah 1000.

Standarisasi dengan Standar Scaler perlu dilakukan  karena adanya perbedaan skala dalam data.
"""

numeric_features = palmoil_df.select_dtypes(include=['number']).columns
numeric_features

scaler = StandardScaler()
palmoil_df[numeric_features] = scaler.fit_transform(palmoil_df[numeric_features])

"""Pembagian data dilakukan dengan rasio 8:2"""

X = palmoil_df.drop(columns=['Price', 'Date'])
y = palmoil_df['Price']

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

print("Jumlah data: ",len(X))
print("Jumlah data latih: ",len(x_train))
print("Jumlah data test: ",len(x_test))

"""## Modelling

### Linear Regression
"""

lr = LinearRegression()
lr.fit(x_train, y_train)

y_pred = lr.predict(x_test)

comparison = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred
}).reset_index(drop=True)

plt.figure(figsize=(12, 6))
plt.plot(comparison['Actual'], label='Actual', color='blue', linestyle='-')
plt.plot(comparison['Predicted'], label='Predicted', color='orange', linestyle='--')
plt.title('Perbandingan Harga Palm Oil: Aktual vs Prediksi (Linear Regression)')
plt.ylabel('Harga')
plt.legend()
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

"""### Random Forest Regression"""

rf = RandomForestRegressor(random_state=42)
rf.fit(x_train, y_train)

y_pred = rf.predict(x_test)

comparison = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred
}).reset_index(drop=True)

plt.figure(figsize=(12, 6))
plt.plot(comparison['Actual'], label='Actual', color='blue', linestyle='-')
plt.plot(comparison['Predicted'], label='Predicted', color='orange', linestyle='--')
plt.title('Perbandingan Harga Palm Oil: Aktual vs Prediksi (Random Forest Regression)')
plt.ylabel('Harga')
plt.legend()
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

"""### SVR"""

svr = SVR()
svr.fit(x_train, y_train)

y_pred = svr.predict(x_test)

comparison = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred
}).reset_index(drop=True)

plt.figure(figsize=(12, 6))
plt.plot(comparison['Actual'], label='Actual', color='blue', linestyle='-')
plt.plot(comparison['Predicted'], label='Predicted', color='orange', linestyle='--')
plt.title('Perbandingan Harga Palm Oil: Aktual vs Prediksi (SVR)')
plt.ylabel('Harga')
plt.legend()
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

"""## Evaluasi

Metrik evaluasi yang digunakan dalam regresi dengan ketiga model di atas adalah MAE, RMSE, dan R-squared.
"""

def evaluate_model(name, model, x_test, y_test):
    y_pred = model.predict(x_test)
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)

    print(f"{name}")
    print(f"MAE  : {mae:.4f}")
    print(f"RMSE : {rmse:.4f}")
    print(f"R²   : {r2:.4f}")

evaluate_model("Linear Regression", lr, x_test, y_test)
evaluate_model("Random Forest", rf, x_test, y_test)
evaluate_model("SVR", svr, x_test, y_test)

"""Berdasarkan metrik evaluasi yang ada, model linear regression adalah model terbaik untuk prediksi harga palm oil.

Melihat korfisien dari model Linear Regression
"""

coef_df = pd.DataFrame({
    'Fitur': x_train.columns,
    'Koefisien': lr.coef_
})
coef_df = coef_df.sort_values(by='Koefisien', ascending=False)

print(coef_df)

"""Diketatui terdapat korelasi positif antara fitur Low, High, dan Vol. terhadap harga palm oil. Terdapat korelasi negatif dari fitur Open terhadap harga palm oil. Tidak ada korelasi antara fitur Change % terhadap perubahan harga palm oil."""